<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE wyniki [
<!ELEMENT wyniki (przedmiot*) >
<!ELEMENT przedmiot (nazwa, egzaminator, rodzaj, ocena) >
<!ELEMENT egzaminator (tytul, imie, nazwisko) >
<!ELEMENT nazwa (#PCDATA) >
<!ELEMENT rodzaj (#PCDATA) >
<!ELEMENT ocena (#PCDATA) >
<!ELEMENT tytul (#PCDATA) >
<!ELEMENT imie (#PCDATA) >
<!ELEMENT nazwisko (#PCDATA) >
<!ENTITY  nd "Niedostateczny">
<!ENTITY  d "Dostateczny">
<!ENTITY  dp "Dostateczny+">
<!ENTITY  db "Dobry">
<!ENTITY  dbp "Dobry+">
<!ENTITY  bd "Bardzo dobry">
<!ENTITY w "Wykład">
<!ENTITY cwa "Cwiczenia audytoryjne">
<!ENTITY cwl "Cwiczenia laboratoryjne">
<!ENTITY m "Magister">
<!ENTITY dr "Doktor">
<!ENTITY drh "Doktor habilitowany">
<!ENTITY dri "Doktor inżynier">
<!ENTITY p "Profesor">
<!ENTITY al "Algorytmy">
<!ENTITY mat "Matematyka">
<!ENTITY sk "Sieci komputerowe">
<!ENTITY so "Systemy opreracyjne">
<!ENTITY xml "XML">
<!ENTITY prog "Programowanie">
]>
<wyniki>
	<przedmiot>
		<nazwa>&al;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Pankracy</imie>
			<nazwisko>Bajeczny</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&db;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&al;</nazwa>
		<egzaminator>
			<tytul>&p;&drh;</tytul>
			<imie>Bianor</imie>
			<nazwisko>Łysy</nazwisko>
		</egzaminator>
		<rodzaj>&cwa;</rodzaj>
		<ocena>&dp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&mat;</nazwa>
		<egzaminator>
			<tytul>&drh;</tytul>
			<imie>Marcel</imie>
			<nazwisko>Chabacki</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&dp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>Matematyka</nazwa>
		<egzaminator>
			<tytul>magister</tytul>
			<imie>Klet</imie>
			<nazwisko>Zabacki</nazwisko>
		</egzaminator>
		<rodzaj>&cwa;</rodzaj>
		<ocena>&dp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&prog;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Amon</imie>
			<nazwisko>Fabacki</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&d;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&prog;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Fidol</imie>
			<nazwisko>Jadacki</nazwisko>
		</egzaminator>
		<rodzaj>&cwa;</rodzaj>
		<ocena>&db;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&prog;</nazwa>
		<egzaminator>
			<tytul>&m;</tytul>
			<imie>Klet</imie>
			<nazwisko>Zabacki</nazwisko>
		</egzaminator>
		<rodzaj>&cwa;</rodzaj>
		<ocena>&dbp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&sk;</nazwa>
		<egzaminator>
			<tytul>&dri;</tytul>
			<imie>Kanizjusz</imie>
			<nazwisko>Miłosierny</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&db;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&sk;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Pankracy</imie>
			<nazwisko>Bajeczny</nazwisko>
		</egzaminator>
		<rodzaj>&cwa;</rodzaj>
		<ocena>&d;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&so;</nazwa>
		<egzaminator>
			<tytul>&dri;</tytul>
			<imie>Ksawery</imie>
			<nazwisko>Melon</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&dbp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>%so;</nazwa>
		<egzaminator>
			<tytul>%dri;</tytul>
			<imie>Ksawery</imie>
			<nazwisko>Melon</nazwisko>
		</egzaminator>
		<rodzaj>&cwa;</rodzaj>
		<ocena>&dbp;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&xml;</nazwa>
		<egzaminator>
			<tytul>&p;,&drh;</tytul>
			<imie>Ramzes</imie>
			<nazwisko>Koniczyna</nazwisko>
		</egzaminator>
		<rodzaj>&w;</rodzaj>
		<ocena>&bd;</ocena>
	</przedmiot>
	<przedmiot>
		<nazwa>&xml;</nazwa>
		<egzaminator>
			<tytul>&dr;</tytul>
			<imie>Scholastyka</imie>
			<nazwisko>Bławatek</nazwisko>
		</egzaminator>
		<rodzaj>ćwiczenia laboratoryjne</rodzaj>
		<ocena>&bd;</ocena>
	</przedmiot>
</wyniki>
